More tweaks to Github action to enable it to run
Signed-off-by: Andy Fingerhut <andy_fingerhut@alum.wustl.edu>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -33,14 +33,15 @@ jobs:
       shell: bash
       run: |
         TAG=""
-        if [[ "$GITHUB_REF" =~ "main" ]]; then
-            TAG="latest"
-        elif [[ "$GITHUB_REF" =~ "stable" ]]; then
-            TAG="stable"
-        else
-            echo "Invalid Github ref $GITHUB_REF"
-            exit 1
-        fi
+        TAG="latest"
+        #if [[ "$GITHUB_REF" =~ "main" ]]; then
+        #    TAG="latest"
+        #elif [[ "$GITHUB_REF" =~ "stable" ]]; then
+        #    TAG="stable"
+        #else
+        #    echo "Invalid Github ref $GITHUB_REF"
+        #    exit 1
+        #fi
         echo "Tag is $TAG"
         echo "tag=$TAG" >> $GITHUB_OUTPUT
     - name: Set up Docker Buildx
