Revert "Improve PI install: use stable branch, parallel build, fix Docker"
This reverts commit c0276baa1e02fb2bad12671fcebf96daef341c7d.

Signed-off-by: sudhanshu shukla <161225935+sudhanshu112233shukla@users.noreply.github.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -43,20 +43,17 @@ jobs:
     - name: Install PI library
       run: |
         git clone https://github.com/p4lang/PI.git /tmp/PI
-        cd /tmp/PI
-        git checkout stable
-        git submodule update --init --recursive
-        ./autogen.sh
-        ./configure
-        make -j$(nproc)
-        sudo make install
-        ls -l /usr/local/include/PI
+        cd /tmp/PI && git submodule update --init --recursive
+        cd /tmp/PI && ./autogen.sh && ./configure && make && sudo make install
+        if [ ! -f /usr/local/include/PI/pi.h ]; then
+          echo "PI headers not found after installation."
+          exit 1
+        fi
     - name: Build test Docker image
       env:
         CC: ${{ matrix.cc }}
         CXX: ${{ matrix.cxx }}
       run: |
-        ./autogen.sh && ./configure
         docker build -t bm --build-arg IMAGE_TYPE=test --build-arg CC=$CC --build-arg CXX=$CXX --build-arg GCOV=$GCOV .
     - name: Run tests with verbose output
       run: |
@@ -79,18 +76,14 @@ jobs:
     - name: Install PI library
       run: |
         git clone https://github.com/p4lang/PI.git /tmp/PI
-        cd /tmp/PI
-        git checkout stable
-        git submodule update --init --recursive
-        ./autogen.sh
-        ./configure
-        make -j$(nproc)
-        sudo make install
-        ls -l /usr/local/include/PI
+        cd /tmp/PI && git submodule update --init --recursive
+        cd /tmp/PI && ./autogen.sh && ./configure && make && sudo make install
+        if [ ! -f /usr/local/include/PI/pi.h ]; then
+          echo "PI headers not found after installation."
+          exit 1
+        fi
     - name: Build Dockerfile.noPI image
-      run: |
-        ./autogen.sh && ./configure
-        docker build -t bm-no-pi --build-arg IMAGE_TYPE=test -f Dockerfile.noPI .
+      run: docker build -t bm-no-pi --build-arg IMAGE_TYPE=test -f Dockerfile.noPI .
     - name: Run tests with verbose output
       run: docker run --rm -w /behavioral-model bm-no-pi /bin/bash -c "make -j$(nproc) VERBOSE=1"
 
@@ -109,14 +102,12 @@ jobs:
     - name: Install PI library
       run: |
         git clone https://github.com/p4lang/PI.git /tmp/PI
-        cd /tmp/PI
-        git checkout stable
-        git submodule update --init --recursive
-        ./autogen.sh
-        ./configure
-        make -j$(nproc)
-        sudo make install
-        ls -l /usr/local/include/PI
+        cd /tmp/PI && git submodule update --init --recursive
+        cd /tmp/PI && ./autogen.sh && ./configure && make && sudo make install
+        if [ ! -f /usr/local/include/PI/pi.h ]; then
+          echo "PI headers not found after installation."
+          exit 1
+        fi
     - name: Build BMv2
       run: |
         ./autogen.sh
